id: P2FFF3E6A
initial_creation_type: ocr
source_metadata:
  volumes:
    1c808fb5f4eb402b91710ddc34b4259d:
      base_file: v115.txt
      image_group_id: I1PD95960
      title: མདོ་སྡེ་དགོངས་པ་ངེས་པར་འགྲེལ་པའི་མདོའི་རྣམ་པར་བཤད་པ།
      total_pages: 1829
      volume_number: 115
